# ----------------------------------
# Initialise the master using kubeadm
# ----------------------------------

- name: Check for existing kubelet configuration
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: kubeadm token generate
  command: kubeadm token generate
  register: token1
  when: kubelet_conf.stat.exists == False

- name: kubeadm get existing token
  command: sh -c "kubeadm token list | awk '/The default bootstrap token/ { print $1; }'"
  register: token2
  when: kubelet_conf.stat.exists == True

# https://github.com/ansible/ansible/issues/4297
- name: token
  set_fact:
    token: "{{ token1 if kubelet_conf.stat.exists == False else token2 }}"

- name: kubeadm init
  command: "kubeadm init --ignore-preflight-errors=cri --token {{ token.stdout }} --kubernetes-version v1.10.0 --apiserver-advertise-address {{ hostvars[groups.master[0]].ansible_ssh_host }} --pod-network-cidr=10.244.0.0/16"
  args:
    creates: /etc/kubernetes/kubelet.conf

# ----------------------------------
# Prepare the shell
# ----------------------------------

- name: Ensure kubectl configuration directory is present
  become: True
  file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0700

- name: Copy kubectl configuration for the default user
  become: True
  copy:
    remote_src: True
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    owner: ubuntu
    group: ubuntu
    mode: 0600

- name: Check for existing kubectl bash completion
  stat:
    path: /etc/bash_completion.d/kubectl
  register: kubectl_bash_completion

- name: Ensure kubectl bash_completion is present
  become: True
  shell: kubectl completion bash > /etc/bash_completion.d/kubectl
  when: kubectl_bash_completion.stat.exists == False

# cf. Token-based discovery with CA pinning: https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/#discovering-what-cluster-ca-to-trust
- name: Obtain CA cert hash
  raw: openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
  register: master_node_ca_hash

